# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kusv_msgs/VisionMark.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VisionMark(genpy.Message):
  _md5sum = "943270e1b6a085921a11b0ebc0a88377"
  _type = "kusv_msgs/VisionMark"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool sign
  # Driving 0
  # Flight 1
int64 height
int64 width
"""
  __slots__ = ['sign','height','width']
  _slot_types = ['bool','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sign,height,width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VisionMark, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sign is None:
        self.sign = False
      if self.height is None:
        self.height = 0
      if self.width is None:
        self.width = 0
    else:
      self.sign = False
      self.height = 0
      self.width = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2q().pack(_x.sign, _x.height, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.sign, _x.height, _x.width,) = _get_struct_B2q().unpack(str[start:end])
      self.sign = bool(self.sign)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2q().pack(_x.sign, _x.height, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.sign, _x.height, _x.width,) = _get_struct_B2q().unpack(str[start:end])
      self.sign = bool(self.sign)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2q = None
def _get_struct_B2q():
    global _struct_B2q
    if _struct_B2q is None:
        _struct_B2q = struct.Struct("<B2q")
    return _struct_B2q
