// Generated by gencpp from file kusv_msgs/DR_data.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_DR_DATA_H
#define KUSV_MSGS_MESSAGE_DR_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kusv_msgs
{
template <class ContainerAllocator>
struct DR_data_
{
  typedef DR_data_<ContainerAllocator> Type;

  DR_data_()
    : header()
    , speed_avr_rear(0.0)
    , yaw_rate(0.0)  {
    }
  DR_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed_avr_rear(0.0)
    , yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _speed_avr_rear_type;
  _speed_avr_rear_type speed_avr_rear;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;





  typedef boost::shared_ptr< ::kusv_msgs::DR_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::DR_data_<ContainerAllocator> const> ConstPtr;

}; // struct DR_data_

typedef ::kusv_msgs::DR_data_<std::allocator<void> > DR_data;

typedef boost::shared_ptr< ::kusv_msgs::DR_data > DR_dataPtr;
typedef boost::shared_ptr< ::kusv_msgs::DR_data const> DR_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::DR_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::DR_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::DR_data_<ContainerAllocator1> & lhs, const ::kusv_msgs::DR_data_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speed_avr_rear == rhs.speed_avr_rear &&
    lhs.yaw_rate == rhs.yaw_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::DR_data_<ContainerAllocator1> & lhs, const ::kusv_msgs::DR_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::DR_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::DR_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::DR_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::DR_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::DR_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::DR_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::DR_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6281181b3ed8c7096c3f94a04025c97";
  }

  static const char* value(const ::kusv_msgs::DR_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6281181b3ed8c70ULL;
  static const uint64_t static_value2 = 0x96c3f94a04025c97ULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::DR_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/DR_data";
  }

  static const char* value(const ::kusv_msgs::DR_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::DR_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 speed_avr_rear\n"
"float64 yaw_rate\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kusv_msgs::DR_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::DR_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed_avr_rear);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DR_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::DR_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::DR_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed_avr_rear: ";
    Printer<double>::stream(s, indent + "  ", v.speed_avr_rear);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_DR_DATA_H
