// Generated by gencpp from file kusv_msgs/LanePointData.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_LANEPOINTDATA_H
#define KUSV_MSGS_MESSAGE_LANEPOINTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace kusv_msgs
{
template <class ContainerAllocator>
struct LanePointData_
{
  typedef LanePointData_<ContainerAllocator> Type;

  LanePointData_()
    : id()
    , frame_id()
    , point()  {
    }
  LanePointData_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , frame_id(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::kusv_msgs::LanePointData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::LanePointData_<ContainerAllocator> const> ConstPtr;

}; // struct LanePointData_

typedef ::kusv_msgs::LanePointData_<std::allocator<void> > LanePointData;

typedef boost::shared_ptr< ::kusv_msgs::LanePointData > LanePointDataPtr;
typedef boost::shared_ptr< ::kusv_msgs::LanePointData const> LanePointDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::LanePointData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::LanePointData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::LanePointData_<ContainerAllocator1> & lhs, const ::kusv_msgs::LanePointData_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.frame_id == rhs.frame_id &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::LanePointData_<ContainerAllocator1> & lhs, const ::kusv_msgs::LanePointData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::LanePointData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::LanePointData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::LanePointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::LanePointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::LanePointData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::LanePointData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::LanePointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c44ef979d32be62ab2486f7d7cc7f22";
  }

  static const char* value(const ::kusv_msgs::LanePointData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c44ef979d32be62ULL;
  static const uint64_t static_value2 = 0xab2486f7d7cc7f22ULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::LanePointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/LanePointData";
  }

  static const char* value(const ::kusv_msgs::LanePointData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::LanePointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"string frame_id\n"
"geometry_msgs/Point[] point\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::kusv_msgs::LanePointData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::LanePointData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.frame_id);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LanePointData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::LanePointData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::LanePointData_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_LANEPOINTDATA_H
