// Generated by gencpp from file kusv_msgs/OptimalBehavior.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_OPTIMALBEHAVIOR_H
#define KUSV_MSGS_MESSAGE_OPTIMALBEHAVIOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kusv_msgs
{
template <class ContainerAllocator>
struct OptimalBehavior_
{
  typedef OptimalBehavior_<ContainerAllocator> Type;

  OptimalBehavior_()
    : header()
    , optimal_behavior(0)  {
    }
  OptimalBehavior_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , optimal_behavior(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _optimal_behavior_type;
  _optimal_behavior_type optimal_behavior;





  typedef boost::shared_ptr< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> const> ConstPtr;

}; // struct OptimalBehavior_

typedef ::kusv_msgs::OptimalBehavior_<std::allocator<void> > OptimalBehavior;

typedef boost::shared_ptr< ::kusv_msgs::OptimalBehavior > OptimalBehaviorPtr;
typedef boost::shared_ptr< ::kusv_msgs::OptimalBehavior const> OptimalBehaviorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::OptimalBehavior_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::OptimalBehavior_<ContainerAllocator1> & lhs, const ::kusv_msgs::OptimalBehavior_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.optimal_behavior == rhs.optimal_behavior;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::OptimalBehavior_<ContainerAllocator1> & lhs, const ::kusv_msgs::OptimalBehavior_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28ab8069ff5ea01ae76ba32c07c3b7da";
  }

  static const char* value(const ::kusv_msgs::OptimalBehavior_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28ab8069ff5ea01aULL;
  static const uint64_t static_value2 = 0xe76ba32c07c3b7daULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/OptimalBehavior";
  }

  static const char* value(const ::kusv_msgs::OptimalBehavior_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 optimal_behavior\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kusv_msgs::OptimalBehavior_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.optimal_behavior);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OptimalBehavior_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::OptimalBehavior_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::OptimalBehavior_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "optimal_behavior: ";
    Printer<int8_t>::stream(s, indent + "  ", v.optimal_behavior);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_OPTIMALBEHAVIOR_H
