// Generated by gencpp from file kusv_msgs/PlanningVision.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_PLANNINGVISION_H
#define KUSV_MSGS_MESSAGE_PLANNINGVISION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kusv_msgs
{
template <class ContainerAllocator>
struct PlanningVision_
{
  typedef PlanningVision_<ContainerAllocator> Type;

  PlanningVision_()
    : header()
    , isStop(false)  {
    }
  PlanningVision_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , isStop(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _isStop_type;
  _isStop_type isStop;





  typedef boost::shared_ptr< ::kusv_msgs::PlanningVision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::PlanningVision_<ContainerAllocator> const> ConstPtr;

}; // struct PlanningVision_

typedef ::kusv_msgs::PlanningVision_<std::allocator<void> > PlanningVision;

typedef boost::shared_ptr< ::kusv_msgs::PlanningVision > PlanningVisionPtr;
typedef boost::shared_ptr< ::kusv_msgs::PlanningVision const> PlanningVisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::PlanningVision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::PlanningVision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::PlanningVision_<ContainerAllocator1> & lhs, const ::kusv_msgs::PlanningVision_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.isStop == rhs.isStop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::PlanningVision_<ContainerAllocator1> & lhs, const ::kusv_msgs::PlanningVision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PlanningVision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PlanningVision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PlanningVision_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "287f58928517f87bf43371625ace1927";
  }

  static const char* value(const ::kusv_msgs::PlanningVision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x287f58928517f87bULL;
  static const uint64_t static_value2 = 0xf43371625ace1927ULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/PlanningVision";
  }

  static const char* value(const ::kusv_msgs::PlanningVision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"bool isStop\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kusv_msgs::PlanningVision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.isStop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanningVision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::PlanningVision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::PlanningVision_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "isStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isStop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_PLANNINGVISION_H
