// Generated by gencpp from file kusv_msgs/PlanningLocalization.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_PLANNINGLOCALIZATION_H
#define KUSV_MSGS_MESSAGE_PLANNINGLOCALIZATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kusv_msgs
{
template <class ContainerAllocator>
struct PlanningLocalization_
{
  typedef PlanningLocalization_<ContainerAllocator> Type;

  PlanningLocalization_()
    : header()
    , lat(0.0)
    , lon(0.0)
    , e(0.0)
    , n(0.0)
    , u(0.0)  {
    }
  PlanningLocalization_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lat(0.0)
    , lon(0.0)
    , e(0.0)
    , n(0.0)
    , u(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _e_type;
  _e_type e;

   typedef double _n_type;
  _n_type n;

   typedef double _u_type;
  _u_type u;





  typedef boost::shared_ptr< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> const> ConstPtr;

}; // struct PlanningLocalization_

typedef ::kusv_msgs::PlanningLocalization_<std::allocator<void> > PlanningLocalization;

typedef boost::shared_ptr< ::kusv_msgs::PlanningLocalization > PlanningLocalizationPtr;
typedef boost::shared_ptr< ::kusv_msgs::PlanningLocalization const> PlanningLocalizationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::PlanningLocalization_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::PlanningLocalization_<ContainerAllocator1> & lhs, const ::kusv_msgs::PlanningLocalization_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.e == rhs.e &&
    lhs.n == rhs.n &&
    lhs.u == rhs.u;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::PlanningLocalization_<ContainerAllocator1> & lhs, const ::kusv_msgs::PlanningLocalization_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d9c8eb59b527fd58780bef211fc5650";
  }

  static const char* value(const ::kusv_msgs::PlanningLocalization_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d9c8eb59b527fd5ULL;
  static const uint64_t static_value2 = 0x8780bef211fc5650ULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/PlanningLocalization";
  }

  static const char* value(const ::kusv_msgs::PlanningLocalization_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 lat\n"
"float64 lon\n"
"\n"
"float64 e\n"
"float64 n\n"
"float64 u\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kusv_msgs::PlanningLocalization_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.e);
      stream.next(m.n);
      stream.next(m.u);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanningLocalization_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::PlanningLocalization_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::PlanningLocalization_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "e: ";
    Printer<double>::stream(s, indent + "  ", v.e);
    s << indent << "n: ";
    Printer<double>::stream(s, indent + "  ", v.n);
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_PLANNINGLOCALIZATION_H
