// Generated by gencpp from file kusv_msgs/PlanningControl.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_PLANNINGCONTROL_H
#define KUSV_MSGS_MESSAGE_PLANNINGCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kusv_msgs
{
template <class ContainerAllocator>
struct PlanningControl_
{
  typedef PlanningControl_<ContainerAllocator> Type;

  PlanningControl_()
    : header()
    , velocity(0.0)
    , str_angle(0.0)  {
    }
  PlanningControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(0.0)
    , str_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _str_angle_type;
  _str_angle_type str_angle;





  typedef boost::shared_ptr< ::kusv_msgs::PlanningControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::PlanningControl_<ContainerAllocator> const> ConstPtr;

}; // struct PlanningControl_

typedef ::kusv_msgs::PlanningControl_<std::allocator<void> > PlanningControl;

typedef boost::shared_ptr< ::kusv_msgs::PlanningControl > PlanningControlPtr;
typedef boost::shared_ptr< ::kusv_msgs::PlanningControl const> PlanningControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::PlanningControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::PlanningControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::PlanningControl_<ContainerAllocator1> & lhs, const ::kusv_msgs::PlanningControl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocity == rhs.velocity &&
    lhs.str_angle == rhs.str_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::PlanningControl_<ContainerAllocator1> & lhs, const ::kusv_msgs::PlanningControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PlanningControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PlanningControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PlanningControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6eb7809a7d6c3e6a259553a266d2235";
  }

  static const char* value(const ::kusv_msgs::PlanningControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6eb7809a7d6c3e6ULL;
  static const uint64_t static_value2 = 0xa259553a266d2235ULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/PlanningControl";
  }

  static const char* value(const ::kusv_msgs::PlanningControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 velocity\n"
"float64 str_angle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kusv_msgs::PlanningControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
      stream.next(m.str_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanningControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::PlanningControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::PlanningControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "str_angle: ";
    Printer<double>::stream(s, indent + "  ", v.str_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_PLANNINGCONTROL_H
