// Generated by gencpp from file kusv_msgs/VisionMark.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_VISIONMARK_H
#define KUSV_MSGS_MESSAGE_VISIONMARK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kusv_msgs
{
template <class ContainerAllocator>
struct VisionMark_
{
  typedef VisionMark_<ContainerAllocator> Type;

  VisionMark_()
    : sign(false)
    , height(0)
    , width(0)  {
    }
  VisionMark_(const ContainerAllocator& _alloc)
    : sign(false)
    , height(0)
    , width(0)  {
  (void)_alloc;
    }



   typedef uint8_t _sign_type;
  _sign_type sign;

   typedef int64_t _height_type;
  _height_type height;

   typedef int64_t _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::kusv_msgs::VisionMark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::VisionMark_<ContainerAllocator> const> ConstPtr;

}; // struct VisionMark_

typedef ::kusv_msgs::VisionMark_<std::allocator<void> > VisionMark;

typedef boost::shared_ptr< ::kusv_msgs::VisionMark > VisionMarkPtr;
typedef boost::shared_ptr< ::kusv_msgs::VisionMark const> VisionMarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::VisionMark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::VisionMark_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kusv_msgs::VisionMark_<ContainerAllocator1> & lhs, const ::kusv_msgs::VisionMark_<ContainerAllocator2> & rhs)
{
  return lhs.sign == rhs.sign &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kusv_msgs::VisionMark_<ContainerAllocator1> & lhs, const ::kusv_msgs::VisionMark_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::VisionMark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::VisionMark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::VisionMark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::VisionMark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::VisionMark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::VisionMark_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::VisionMark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "943270e1b6a085921a11b0ebc0a88377";
  }

  static const char* value(const ::kusv_msgs::VisionMark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x943270e1b6a08592ULL;
  static const uint64_t static_value2 = 0x1a11b0ebc0a88377ULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::VisionMark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/VisionMark";
  }

  static const char* value(const ::kusv_msgs::VisionMark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::VisionMark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool sign\n"
"  # Driving 0\n"
"  # Flight 1\n"
"int64 height\n"
"int64 width\n"
;
  }

  static const char* value(const ::kusv_msgs::VisionMark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::VisionMark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sign);
      stream.next(m.height);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionMark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::VisionMark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::VisionMark_<ContainerAllocator>& v)
  {
    s << indent << "sign: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sign);
    s << indent << "height: ";
    Printer<int64_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int64_t>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_VISIONMARK_H
