// Generated by gencpp from file sve_design_control/driving_control_msg.msg
// DO NOT EDIT!


#ifndef SVE_DESIGN_CONTROL_MESSAGE_DRIVING_CONTROL_MSG_H
#define SVE_DESIGN_CONTROL_MESSAGE_DRIVING_CONTROL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sve_design_control
{
template <class ContainerAllocator>
struct driving_control_msg_
{
  typedef driving_control_msg_<ContainerAllocator> Type;

  driving_control_msg_()
    : velocity(0.0)
    , steering_angle(0.0)  {
    }
  driving_control_msg_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::sve_design_control::driving_control_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sve_design_control::driving_control_msg_<ContainerAllocator> const> ConstPtr;

}; // struct driving_control_msg_

typedef ::sve_design_control::driving_control_msg_<std::allocator<void> > driving_control_msg;

typedef boost::shared_ptr< ::sve_design_control::driving_control_msg > driving_control_msgPtr;
typedef boost::shared_ptr< ::sve_design_control::driving_control_msg const> driving_control_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sve_design_control::driving_control_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sve_design_control::driving_control_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sve_design_control::driving_control_msg_<ContainerAllocator1> & lhs, const ::sve_design_control::driving_control_msg_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sve_design_control::driving_control_msg_<ContainerAllocator1> & lhs, const ::sve_design_control::driving_control_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sve_design_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sve_design_control::driving_control_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sve_design_control::driving_control_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sve_design_control::driving_control_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb8ec87b60030ed9d49e286c9809454c";
  }

  static const char* value(const ::sve_design_control::driving_control_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb8ec87b60030ed9ULL;
  static const uint64_t static_value2 = 0xd49e286c9809454cULL;
};

template<class ContainerAllocator>
struct DataType< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sve_design_control/driving_control_msg";
  }

  static const char* value(const ::sve_design_control::driving_control_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocity\n"
"float32 steering_angle\n"
;
  }

  static const char* value(const ::sve_design_control::driving_control_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct driving_control_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sve_design_control::driving_control_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sve_design_control::driving_control_msg_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SVE_DESIGN_CONTROL_MESSAGE_DRIVING_CONTROL_MSG_H
