(cl:in-package kusv_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SPEEDFR-VAL
          SPEEDFR
          SPEEDFL-VAL
          SPEEDFL
          SPEEDRR-VAL
          SPEEDRR
          SPEEDRL-VAL
          SPEEDRL
          SPEED_AVR_R-VAL
          SPEED_AVR_R
          LAT_ACC_SPEED-VAL
          LAT_ACC_SPEED
          PARKING_BRAKE_ON-VAL
          PARKING_BRAKE_ON
          AIR_COND_ON-VAL
          AIR_COND_ON
          STEERING_WHEEL_ANGLE-VAL
          STEERING_WHEEL_ANGLE
          STEERING_WHEEL_ANGULAR-VAL
          STEERING_WHEEL_ANGULAR
          STEERING_WHEEL_TQ-VAL
          STEERING_WHEEL_TQ
          POS_ACC_PEDAL-VAL
          POS_ACC_PEDAL
          BRAKE_ACTIVE_STATE-VAL
          BRAKE_ACTIVE_STATE
          BRAKE_CYLINDER_PRESS-VAL
          BRAKE_CYLINDER_PRESS
          ENGINE_SPEED-VAL
          ENGINE_SPEED
          GEAR_TRANS_STATE-VAL
          GEAR_TRANS_STATE
          GEAR_SELDISP-VAL
          GEAR_SELDISP
          POS_THROTTLE-VAL
          POS_THROTTLE
          CLUSTER_ODOMETER-VAL
          CLUSTER_ODOMETER
          LON_ACC_SPEED-VAL
          LON_ACC_SPEED
          VEHICLE_SPEED_ENGINE-VAL
          VEHICLE_SPEED_ENGINE
          YAW_RATE-VAL
          YAW_RATE
))